export const PROPERTIES = 'PROPERTIES';
export const GET_FILTERED_PROPERTIES = 'GET_FILTERED_PROPERTIES';
export const GET_SEARCHED_POST = 'GET_SEARCHED_POST';
export const GET_NEXT_OR_PREVIOUS_PAGE = 'GET_NEXT_OR_PREVIOUS_PAGE';
export const GET_COORDINATES = 'GET_COORDINATES';
